#!/bin/bash
#----------------------- Variablen --------------------------------------------------------------------------------#
# SET-X damit die Ausfuehrung protokolliert wird
set -x


#-----------------------------------------------------------------------------------------------------------------#

# mount the SMB share of tkfileserevr for paperless 
# $0 = Aufrufzeile
# $1 = ID der VM
# $2 = status
if [ $2 == "pre-start" ]; then     
  /usr/bin/mount /mnt/paperless/
fi

exit 0
